// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	httpservice "github.eagleview.com/engineering/assess-platform-library/httpservice"
)

// AuthTokenInterface is an autogenerated mock type for the AuthTokenInterface type
type AuthTokenInterface struct {
	mock.Mock
}

// AddAuthorizationTokenHeader provides a mock function with given fields: ctx, httpClient, headers, appCode, clientID, clientSecret
func (_m *AuthTokenInterface) AddAuthorizationTokenHeader(ctx context.Context, httpClient httpservice.IHTTPClientV2, headers map[string]string, appCode string, clientID string, clientSecret string) error {
	ret := _m.Called(ctx, httpClient, headers, appCode, clientID, clientSecret)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, httpservice.IHTTPClientV2, map[string]string, string, string, string) error); ok {
		r0 = rf(ctx, httpClient, headers, appCode, clientID, clientSecret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
