// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ISlackClient is an autogenerated mock type for the ISlackClient type
type ISlackClient struct {
	mock.Mock
}

// SendErrorMessage provides a mock function with given fields: errorCode, reportId, workflowId, lambdaName, taskName, msg, meta
func (_m *ISlackClient) SendErrorMessage(errorCode int, reportId string, workflowId string, lambdaName string, taskName string, msg string, meta map[string]string) {
	_m.Called(errorCode, reportId, workflowId, lambdaName, taskName, msg, meta)
}
